[package]
name = "wasm-devices"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Required to compile to .wasm file.

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }