[package]
name = "snakeway"
version = "0.1.0"
edition = "2024"

[features]
default = []
wasm = ["snakeway-core/wasm"]

[dependencies]
snakeway-core = { version = "*", path = "../snakeway-core" }
clap = { workspace = true, features = ["derive"] }

[[bin]]
name = "snakeway"
path = "src/main.rs"
