[package]
name = "snakeway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
pingora = { workspace = true, features = ["proxy"] }
serde = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true , features = ["fmt", "json", "env-filter"]}
