[package]
name = "snakeway"
version = "0.1.0"
edition = "2024"

[dependencies]

config = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
pingora = { workspace = true }
pingora-core = { workspace = true }