[server]
version = 1
threads = 4
pid_file = "/tmp/snakeway.pid"

[[listener]]
addr = "127.0.0.1:8080"

[[listener]]
addr = "127.0.0.1:8443"
tls = { cert = "./data/certs/snakeway.pem", key = "./data/certs/snakeway.key" }

[include]
routes = "routes/*.toml"
services = "services/*.toml"
devices = "devices/*.toml"
