[server]
listen = "127.0.0.1:8443"
threads = 4
pid_file = "/tmp/snakeway.pid"

[server.tls]
cert = "./snakeway.pem"
key  = "./snakeway.key"

[include]
routes = "routes/*.toml"
services = "services/*.toml"
devices = "devices/*.toml"
