[identity_device]
# Whether this device is enabled and active.
enable = true

# Enables or disables GeoIP lookup for client IP addresses.
enable_geoip = false

# A list of trusted proxy IP addresses or CIDR ranges.
# Defines which intermediate servers are allowed to be believed when determining the real client IP from X-Forwarded-For.
# To put it another way, if an IP is in trusted_proxies, Snakeway assumes it is allowed to lie on behalf of the client.
trusted_proxies = []

# Whether user agent parsing is enabled.
enable_user_agent = true

# The user agent parser engine to use (woothee or uaparser).
ua_engine = "woothee"
