[structured_logging_device]
# Whether this device is enabled and active.
enable = true

# Whether to include HTTP headers in the structured logs.
include_headers = false

allowed_headers = []

redacted_headers = []

level = "info"

# Whether to include identity information in the structured logs.
include_identity = false

identity_fields = ["country", "region", "asn", "device", "bot"]