[structured_logging_device]
# Whether this device is enabled and active.
enable = true

# include_headers: Whether to include HTTP headers in the structured logs.
include_headers = false

# Logging level, e.g., error, info, warning
level = "error"

identity_fields = ["country", "region", "asn", "device", "bot"]
