[server]
version = 1
# Pid is optional, but necessary for the snakeway reload command.
pid_file = "/tmp/snakeway.pid"
# The number of worker threads for handling requests.
# If unset, Pingora decides how many threads to use.
threads = 8
# Root CA used by Pingora to verify upstream certificates.
# ca_file = "/path/to/certs/ca.pem"


# Modular inclusion for routes, services, and devices.
[include]
routes = "routes.d/*.toml"
services = "services.d/*.toml"
devices = "devices.d/*.toml"
ingress = "ingress.d/*.toml"
