[server]
version = 1
# Pid is optional, but necessary for the snakeway reload command.
pid_file = "/tmp/snakeway.pid"
# The number of worker threads for handling requests.
# If unset, Pingora decides how many threads to use.
threads = 8

[[listener]]
addr = "127.0.0.1:8080"

# A second listener with a TLS configuration for encryption.
# [[listener]]
# addr = "127.0.0.1:8443"
# tls = { cert = "./path/to/tls_cert.pem", key = "./path/to/tls_cert.key" }

# Modular inclusion for routes, services, and devices.
[include]
routes = "routes/*.toml"
services = "services/*.toml"
devices = "devices/*.toml"
