[server]
version = 1
threads = 4
pid_file = "/tmp/snakeway.pid"

[[listener]]
addr = "127.0.0.1:8080"

[[listener]]
addr = "127.0.0.1:8443"
tls = { cert = "./path/to/tls_cert.pem", key = "./path/to/tls_cert.key" }

[include]
routes = "routes/*.toml"
services = "services/*.toml"
devices = "devices/*.toml"
