[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
snakeway-core = { version = "*", path = "../snakeway-core", features = ["wasm", "static_files"] }
tracing-subscriber = "0.3"
tracing = "0.1"
pretty_assertions = "1"
serde_json = "1.0.145"
once_cell = "1.21.3"
tempfile = "3.23.0"