[[device]]
name = "identity"
type = "builtin"
builtin = "identity"
enabled = true

[device.config]
trusted_proxies = ["10.0.0.0/8"]
geoip = true
user_agent = "woothee"

[[device]]
name = "structured_logging"
type = "builtin"
builtin = "structured_logging"
enabled = true

[device.config]
format = "json"
include_headers = true
